version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://deakinlab_n7w5_user:I0NHfqcbJRZaGIDOrr6UAGfwpyzjipWZ@postgres:5432/deakinlab_n7w5  
    depends_on:
      - postgres

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://deakinlab_n7w5_user:I0NHfqcbJRZaGIDOrr6UAGfwpyzjipWZ@postgres:5432/deakinlab_n7w5 
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: deakinlab_n7w5
      POSTGRES_USER: deakinlab_n7w5_user
      POSTGRES_PASSWORD: I0NHfqcbJRZaGIDOrr6UAGfwpyzjipWZ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
